name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install Pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.0

      - name: Install step
        run: "pnpm install"


      - name: Build step
        run: "pnpm build"


      # - name: Static Deployment
      #   run: deployctl deploy --project="hoshiki-astro-deno-16" https://jsr.io/@std/http/1.0.7/file_server.ts
      # deployctl deploy --project=<your-preferred-project-name> https://jsr.io/@std/http/1.0.7/file_server.ts
      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "hoshiki-astro-deno-16"
          # entrypoint: "index.html"
          root: "dist"
